### ISSUE TITLE
missing function 

### ISSUE THREAD

**Issue by thakurs22** [mrshub/SimnTG#1]
Thanks for this code. When i run Sim_ code, error with the function call 'gausmult'. Not sure if i miss to identify. 
Thanks for the help! Sunitha

**Comment by mrshub** [comment]
Hi @thakurs22, 

We have reached out to the code developer Ron Ouwerkerk in the MRSHub forum: https://forum.mrshub.org/t/code-submission/206/2

We'll update you when we hear back from him.

Best,
Georg (MRSHub team)
